### Obtener todos los usuarios
GET http://localhost:8081/api/usuarios


### Obtener un usuario por su id
GET http://localhost:8081/api/usuarios/1


### Crear un usuario
POST http://localhost:8081/api/usuarios
Content-Type: application/json


{
  "nombre": "Juan",
  "ciudad": "Pereira",
  "direccion": "Calle 456",
  "email": "juan@email.com",
  "password": "987654321"
}


### Actualizar un usuario
PUT http://localhost:8081/api/usuarios
Content-Type: application/json


{
  "id": 1,
  "nombre": "Carlos",
  "ciudad": "Armenia",
  "direccion": "Nueva dirección"
}


### Eliminar un usuario
DELETE http://localhost:8081/api/usuarios/1





### Obtener todos los usuarios que tengan un nombre dado
GET http://localhost:8081/api/usuarios?nombre=Carlos


### Obtener todos los usuarios cuya ciudad de residencia sea Armenia
GET http://localhost:8081/api/usuarios?ciudad=Armenia


### Obtener todos los usuarios cuya ciudad de residencia sea Armenia y su nombre sea Carlos
GET http://localhost:8081/api/usuarios?ciudad=Armenia&nombre=Carlos